### ISSUE TITLE
version 1.0.4 doesn't support latest version of Grammy (1.13.1)

### ISSUE THREAD

**Issue by fedor-pavlov** [grammyjs/files#1]
Type 'import("https://deno.land/x/grammy@v1.13.1/core/api").Api<import("https://deno.land/x/grammy@v1.13.1/core/client").RawApi>' does not satisfy the constraint 'import("https://deno.land/x/grammy@v1.11.2/core/api").Api<import("https://deno.land/x/grammy@v1.11.2/core/client").RawApi>'.
  The types of 'raw.setWebhook' are incompatible between these types.
    Type '(args: { url: string; certificate?: import("https://deno.land/x/grammy@v1.13.1/types.deno").InputFile | undefined; ip_address?: string | undefined; max_connections?: number | undefined; allowed_updates?: readonly ("message" | ... 12 more ... | "chat_join_request")[] | undefined; drop_pending_updates?: boolean | unde...' is not assignable to type '(args: { url: string; certificate?: import("https://deno.land/x/grammy@v1.11.2/types.deno").InputFile | undefined; ip_address?: string | undefined; max_connections?: number | undefined; allowed_updates?: readonly ("message" | ... 12 more ... | "chat_join_request")[] | undefined; drop_pending_updates?: boolean | unde...'.
      Types of parameters 'args' and 'args' are incompatible.
        Type '{ url: string; certificate?: import("https://deno.land/x/grammy@v1.11.2/types.deno").InputFile | undefined; ip_address?: string | undefined; max_connections?: number | undefined; allowed_updates?: readonly ("message" | ... 12 more ... | "chat_join_request")[] | undefined; drop_pending_updates?: boolean | undefined; ...' is not assignable to type '{ url: string; certificate?: import("https://deno.land/x/grammy@v1.13.1/types.deno").InputFile | undefined; ip_address?: string | undefined; max_connections?: number | undefined; allowed_updates?: readonly ("message" | ... 12 more ... | "chat_join_request")[] | undefined; drop_pending_updates?: boolean | undefined; ...'.
          Types of property 'certificate' are incompatible.
            Type 'import("https://deno.land/x/grammy@v1.11.2/types.deno").InputFile | undefined' is not assignable to type 'import("https://deno.land/x/grammy@v1.13.1/types.deno").InputFile | undefined'.
              Property '[toRaw]' is missing in type 'import("https://deno.land/x/grammy@v1.11.2/types.deno").InputFile' but required in type 'import("https://deno.land/x/grammy@v1.13.1/types.deno").InputFile'.deno-ts(2344)

**Comment by fedor-pavlov** [comment]
It looks like the following plugins are linked to old version (1.11.2) of Grammy:
1) files v.1.0.4 (https://deno.land/x/grammy_files@v1.0.4/mod.ts)
2) conversations v.1.1.0 (https://deno.land/x/grammy_conversations@v1.1.0/mod.ts)

**Comment by KnorpelSenf** [comment]
This is incorrect. Update your dependencies and run your app with `--reload`.
