### ISSUE TITLE
Any plans to make this edge compatible? 

### ISSUE THREAD

**Issue by ElasticBottle** [grammyjs/files#11]
![image](https://github.com/grammyjs/files/assets/44563205/dd73b3e1-62af-4812-90cf-0147b6972f4b)

Trying to run this on cloudflare workers today, but am running into the errors above.

I do believe adding the `node:fs` etc. prefixes to the imports should allow the `nodejs_compat` layer of wrangler to takeover and work it's magic. Not 100% if all the node imports used is polyfilled by wrangler though.

**Comment by KnorpelSenf** [comment]
The ~30 lines in https://github.com/grammyjs/files/blob/main/src/deps.node.ts are all you need to look at if you want to improve compatibility of the npm build. I'd be happy to review a pull request that adds CFW compatibility!

**Comment by KnorpelSenf** [comment]
We're gonna change the build system substantially for 2.0, and drop support for many old versions of Node. This will be fixed implicitly by then, so we do not need to track it.

**Comment by KnorpelSenf** [comment]
Wait why do you need the plugin on CFW anyway? There's no real persistent file system there, is it?

**Comment by KnorpelSenf** [comment]
I think you can just call `getUrl` instead of `download`. This should work already. Then you can stream the fetch response of it anywhere you like. That is much more efficient than downloading the file entirely.
