### ISSUE TITLE
bug: Incorrect file URL

### ISSUE THREAD

**Issue by yevheniikulisidi** [grammyjs/files#7]
When a bot class has an environment variable `test`:
```typescript
const bot = new Bot<MyContext>(token, {
  client: { environment: environment === 'production' ? 'prod' : 'test' }
});
```

Using this code:
```typescript
const file = await ctx.getFile();
const fileUrl = file.getUrl();
```

The `fileUrl` variable is `https://api.telegram.org/file/bot<token>/<file_path>`
It should be `https://api.telegram.org/file/bot<token>/test/<file_path>`

**Comment by KnorpelSenf** [comment]
You need to configure the files plugin in the same way you configure the bot.

However, `environment` is actually not supported by the plugin yet. I will quickly add it.

**Comment by KnorpelSenf** [comment]
@yevheniikulisidi can you run
```sh
npm install github:grammyjs/files#env
```
and see if that allows you to configure the plugin correctly? Use
```ts
hydrateFiles(bot.token, {
  client: { environment: environment === 'production' ? 'prod' : 'test' }
})
```
and please approve #8 if that fixes your problem.

**Comment by yevheniikulisidi** [comment]
@KnorpelSenf It's not working!

**Comment by KnorpelSenf** [comment]
Remember that when you say it “doesn't work”, we cannot login to your computer and figure out what's wrong. You need to explain what you are doing, what you are expecting to happen, and what is actually happening. If there's an error, share the full error message, too :)
